spring:
    #rabbitmq Development environment
   rabbitmq:
    host: 192.168.2.8
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
   jpa:
    database: MYSQL
   #master Database development environment
   datasource:
   # The following is a supplementary setting for the connection pool, applied to all data sources above
      type: com.alibaba.druid.pool.DruidDataSource
# Initialization size, minimum, maximum
      initialSize: 10
      minIdle: 10
      maxActive: 50
      # Configure the time to get connection timeout
      maxWait: 60000
      # How long does the configuration interval take to perform a test and detect idle connections that need to be closed in milliseconds?
      timeBetweenEvictionRunsMillis: 60000
      # Configure the minimum lifetime for a connection in the pool, in milliseconds
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # Open the PSCache and specify the size of the PSCache on each connection. If you use Oracle, configure poolPreparedStatements to true and mysql to false. Databases with more sub-databases are recommended to be configured as false.
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      # Configure monitoring statistics interception filters, remove the monitoring interface sql can not be statistical, 'wall' for the firewall stat, wall, log4j2, slf4j
      filters: wall,stat,log4j2
      # Open the mergeSql function via the connectProperties property; slow SQL records
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # Merge monitoring data of multiple DruidDataSources
      useGlobalDataSourceStat: true
      driver-class-name:  com.mysql.jdbc.Driver

   master:
      datasource:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/%s?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
   #slave Database development environment
   slave:
      datasource:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/%s?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  #redis Configuration
  redis:
    # Redis Database index (default is 0)
    database: 0
    # Redis server address
    host: localhost
    # Redis Server connection port
    port: 6379
    # Redis 服务器连接密码（默认为空）
    password: 123456
    # Maximum number of connection pool connections (using a negative value means no limit)
    max-active: 300
    # Connection pool maximum blocking wait time (use negative value means there is no limit -1)
    max-wait: 10000
    # Maximum idle connection in the connection pool
    max-idle: 100
    # The minimum idle connection in the connection pool
    min-idle: 0
    # Connection timeout (milliseconds)
    timeout:  0