spring:
  application:
    name: hystrix-dashboard-turbine
server:
  port: 8182
turbine:
  #Configure the list of serviceIds in Eureka to indicate which services to monitor
  app-config: service-provider1,service-provider2
  #Specify which clusters to aggregate. Multiple use "," split, the default is default. Can be accessed using http://.../turbine.stream?cluster=one of {clusterConfig}
  aggregator:
    cluster-config: default
  #1. clusterNameExpression specifies the cluster name, the default expression appName;
  #At this point: turtle.aggregator.clusterConfig needs to configure the application name you want to monitor;
  #2. When clusterNameExpression: default, turbine.aggregator.clusterConfig can not write, because the default is default;
  #3. When using clusterNameExpression:metadata[‘cluster’], suppose the application you want to monitor is configured with eureka.instance.metadata-map.cluster: ABC.
  # You need to configure while the turbine.aggregator.clusterConfig: ABC
  cluster-name-expression: new String("default")