spring:
  application:
    name: cloud-server-zuul
server:
  port: 8763
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/

#zuul.ignored-patterns=/**/hello/**
#zuul.routes.hello-service.url=forward:/local
#zuul.retryable=false
#zuul.routes.hello-service.retryable=false


#zuul.routes.hello-service.path=/hello-service/**
#zuul.routes.hello-service.service-id=hello-service
#ribbon.eureka.enabled=false
#hello-service.ribbon.listOfServers= http://localhost:8080/,http://localhost:8081/

zuul:
  routes:
    service-provider:
      path: /service-provider/**
      url: http://localhost:9001/
    service-consumer:
      path: /service-consumer/**
      url: http://localhost:9002/

