server:
  port: 9003
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: service-upload
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 6MB
      enabled: true
