spring:
  application:
    name: cloud-server-config
  cloud:
    config:
      server:
        git:
          # GIT warehouse
          uri: https://github.com/efengx/spring-cloud-groovy.git
          # Configuration file repository
          search-paths: config-repo

server:
  port: 8083


#spring.cloud.config.server.health.repositories.check.name=configclient
#spring.cloud.config.server.health.repositories.check.label=master
#spring.cloud.config.server.health.repositories.check.profiles=dev
#close health examination
#spring.cloud.config.server.health.enabled=false

#spring.cloud.config.username=user
#spring.cloud.config.password=37cc5635-559b-4e6f-b633-7e932b813f73

#eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8080/eureka/
#,http://localhost:1112/eureka/

