spring:
  application:
    name: cloud-server-eureka
server:
  port: 8761
eureka:
#  server:
#  Close the protection mechanism
#    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
  #    region: eureka
  #    No registration required
      register-with-eureka: false
  #    Close search service
      fetch-registry: false
      serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:8761/eureka/
