spring:
  application:
    name: service-consumer
  cloud:
    config:
      #The {label} section in the corresponding profile rule
      label: master
      #The {profile} section in the corresponding profile rule
      profile: dev
      uri: http://localhost:8083/
server:
  port: 9002
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8080/eureka/

